### ISSUE TITLE
Blocks page - Missing elements in table rows

### ISSUE THREAD

**Issue by J-G-W** [CityOfZion/dora#105]
@comountainclimber 

Each row is missing the following:

- The pink strip on each table row missing
- Icon missing
- Time and date icons missing
- The pink arrow at the right side of each row missing

![image](https://user-images.githubusercontent.com/36457062/87709334-0622f000-c79c-11ea-92f6-6af4aefcba35.png)

![image](https://user-images.githubusercontent.com/36457062/87709365-120eb200-c79c-11ea-9802-d1063b1f0dd8.png)

This is consistent across Safari Version 13.1.1 (15609.2.9.1.2) MAC OS Catalina V 10.15.5 and Google Chrome Version 83.0.4103.116 (Official Build) (64-bit) MAC OS Catalina V 10.15.5

**Comment by ixje** [comment]
looks to be resolved
