### ISSUE TITLE
Mobile footer link formatting

### ISSUE THREAD

**Issue by J-G-W** [CityOfZion/dora#131]
@comountainclimber The links look a little out of position on mobile.
![IMG_8110FDFAE7A7-1](https://user-images.githubusercontent.com/36457062/88907938-24cfbf00-d251-11ea-81e2-9adf0a623bf4.jpeg)

**Comment by picarodias** [comment]
Align the Blocks links to the rest of the list:
- Contracts
- Transactions
- **Blocks**
- More Information
