### ISSUE TITLE
feature: implement basic UI page scaffolding for monitor page

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/dora#262]
This issue is dependent on #238 but after that is completed basic implementation of the mock below can be completed

![image (3).png](https://images.zenhubusercontent.com/60218d1a99afe4b68a456c99/31bb0948-c19b-4bc9-a59a-d128af9c4dc2)

NOTES:
- Do not implement the following UI elements:
![Screen Shot 2021-03-11 at 8.00.24 AM.png](https://images.zenhubusercontent.com/60218d1a99afe4b68a456c99/ee197668-191e-4c71-8d72-dd3ead6ece77)

- ![Screen Shot 2021-03-11 at 8.00.19 AM.png](https://images.zenhubusercontent.com/60218d1a99afe4b68a456c99/7e9f4673-751a-4d24-9598-e048875e1f1b)

- ![Screen Shot 2021-03-11 at 8.00.13 AM.png](https://images.zenhubusercontent.com/60218d1a99afe4b68a456c99/70a88722-c858-4942-ba89-0a176285bfdd)

Mock data can be used to complete this task until the redux state feature is complete.

**Comment by lllwvlvwlll** [comment]
resolved
