### ISSUE TITLE
create component element list

### ISSUE THREAD

**Issue by endkeyCoder** [CityOfZion/dora#281]
**Summary or problem description**
This issue is covering the redesign effort of the Endpoint list section, inside the Monitor page.

**Do you have any solution you want to propose?**
The Endpoint list section will contain the following columns:

- **Endpoint** - This column will display the addresses of all the available and unavailable nodes.
- **Type** - This is the API type (REST or RPC).
- **Is it up?** - Represents whether the server is up or down with corresponding icons. It can change each time the server is polled. The Status field in the API should map to the following icons on the Front End:

    1. OK -> Green checkmark icon
    2. Stateheight stalled -> Yellow checkmark icon
    3. Stateheight lagging -> Green checkmark icon
    4. Stalled -> Red X icon
    5. Invalid SSL cert -> Red X icon
    6. Wrong hostname in SSL cert -> Red X icon
    7. Unreachable -> Red X icon

- **Availability** - This is the percentage of requests answered / requests made as long as the monitor backend has been up. We should display its label as Availability (as it is on the API) instead of Reliability, as it's shown in the desig. As agreed before with COZ team, at least for the first release, we will show this as percentage and not an icon as shown in the designs.
- **State Height** - The state height is the highest block that has passed state-checking verification, meaning there are no errors found in the chain storage state up to that block. It always lags behind the block height because it takes some time to calculate the state hash. As agreed before with COZ team, at least for the first release, we will show this as a number (like Block Height), and not an icon as shown in the designs.
- **Block Height** -  Refers to the number of blocks that have been confirmed in the Neo blockchain, from the genesis block to the most recent one. In the API this number is being referred as "Height"
- **Version** - The version of the Neo blockchain.
- **Peers** - The number of peer nodes connected to each endpoint, hosting ledger and smart contracts.

**Comment by rssavietto** [comment]
@endkeyCoder Hi Kenedy, please note that the column currently labeled Reliability should be relabeled as Availability.

**Comment by comountainclimber** [comment]
@Thacryba this PR adds support for every country in the world => https://github.com/CityOfZion/dora/pull/302
