### ISSUE TITLE
Mobile - Main page

### ISSUE THREAD

**Issue by rssavietto** [CityOfZion/dora#315]
#### **Functional requirements**
The purpose of this issue is to implement the mobile version of Monitor's main page. Most of the elements already used in the desktop version are going to be present in the mobile one, with a couple of differences listed below:

- We will only show the columns **Endpoint**, **Is it up?** and **Availability**. The remaining columns will be shown in a separate details modal, handled in issue #316
- There will be an arrow at the right of each row in the table, however clicking **anywhere** on the row will take the user to the details modal

#### **Designs** 
Designs can be found [here](https://tools.avocode.com/comment/groups/fde325cdc37a48508111330e6acd863f?artboardOriginalId=3C80225C-8854-4687-B262-4F60638AE84A&theme=light).

**Comment by brunobass123** [comment]
- correção do filtro Mainnet ( esta muito colado ) 
![image](https://user-images.githubusercontent.com/74265602/117338321-d05b0f00-ae74-11eb-80bb-2f81395dcd95.png)
- Corrigir exibição do icone copy 
- Corrigir funcionalidade copy ( atualmente n funciona )
