### ISSUE TITLE
Flag icons are not loading for Chrome users on Windows

### ISSUE THREAD

**Issue by rssavietto** [CityOfZion/dora#325]
**Env.:** Test and Production
**Browser:** Chrome Version 90.0.4430.93 . If it helps troubleshooting the issue, it also happens on Edge.
**OS:** Windows 10

This issue does not happen on Firefox using Windows and, according to Kenedy, it does not happen using Chrome on a Mac either.

![image.png](https://images.zenhubusercontent.com/6026cbb80742b10950a4be63/4d56f0b8-44fb-4f72-9ab6-0ee45cbae382)

**Comment by rssavietto** [comment]
Hey @comountainclimber, fyi.
Not exactly sure to whom this should be assigned to, so I'm leaving it in the Triage for now. Let me know if this is something that we should take a look at.

**Comment by comountainclimber** [comment]
I can take care of this one thank you for reporting

**Comment by lock9** [comment]
![image](https://user-images.githubusercontent.com/38396062/132936617-30e68a01-7fa7-4c67-8cd6-584615e1339b.png)
