### ISSUE TITLE
N3 transaction page should show signature scope

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/dora#345]
N3 transactions have a signature scope, such as "CalledByEntry" or "Global". This is already part of the transaction endpoint and could be displayed on the transaction page.

**Comment by lock9** [comment]
I think we can close this one. @hal0x2328 could you verify if this has been implemented correctly, and if so, close this?
Thanks

**Comment by lock9** [comment]
Hi Joe, I will close this because I have verified that the feature is present. Feel free to reopen it.
