### ISSUE TITLE
NEO legacy transaction not rendering correctly

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/dora#354]
https://dora.coz.io/transaction/neo2/mainnet/307895d37923862aafcabc9ce377c537a99aca1ddcad95248c09cbfd74a6c131

This transaction should have 1 input (140 GAS) and three outputs (46.6666666x GAS each) and it looks like the API is returning the correct data => https://dora.coz.io/api/v1/neo2/mainnet/transaction_abstracts/307895d37923862aafcabc9ce377c537a99aca1ddcad95248c09cbfd74a6c131

**Comment by endkeyCoder** [comment]
hi i have a question
if you keep the code snippet below
![Captura de Tela 2021-07-15 às 10 57 43](https://user-images.githubusercontent.com/57366068/125800453-7e5af7e5-5030-4888-a402-25cf48090162.png)
the result stay strange
![Captura de Tela 2021-07-15 às 11 04 17](https://user-images.githubusercontent.com/57366068/125801417-5f076d43-4db7-4a60-96de-6a1de3bfd2c0.png)
but if remove this code the information make more sense
![Captura de Tela 2021-07-15 às 11 05 39](https://user-images.githubusercontent.com/57366068/125801669-b2fbdda0-6328-4d35-81c3-8bb5c36ab7af.png)
my question is, what the objective this code? It is really necessary?

**Comment by endkeyCoder** [comment]
Hi @comountainclimber welcome back! Can you help us with this question? We have a PR ready for this but we wanted to confirm this subject with you before sending it ahead

**Comment by comountainclimber** [comment]
Sorry must have missed this... Lets go ahead and remove the code that is causing the bug! Thank you for double checking 🙏
