### ISSUE TITLE
Monitor NaN block time and best block = 0

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/dora#367]
Occasionally on page load, the monitor presents the following:

* *Best Block:* `0`
* *Avg Block Time:* `NaN seconds`

This is most likely associated with a race condition in the application and/or a `divide by zero` scenario(for avg block time).

To mitigate, we should populate placeholder copy or graphic.

**Comment by lock9** [comment]
This has been done and merged, but has not been released. Works fine on localhost.
