### ISSUE TITLE
Provide a link to the address page from the contract page

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/dora#395]
It would be useful to include a link to the `address` page for the address of any given smart contract converted from its scripthash, so that users can easily find the token balances held in the contract as well as transfers of funds to and from the contract.

**Comment by lock9** [comment]
On the contracts page, where we see the "contract", do 2 things:
- Put the title on the left of the hash (make it a single line)
- Make the title White instead of purple
- Make the hash purple and make it a link to the equivalent  that  scripthash address

**Comment by ixje** [comment]
The link exists, but the translation is wrong. To be fixed in https://github.com/CityOfZion/dora/issues/615
