### ISSUE TITLE
Separate testnet vs mainnet

### ISSUE THREAD

**Issue by jastez** [CityOfZion/dora#396]
Steps to repro:
1) Filter for a given chain (testnet, mainnet etc)
2) pick an item from the list on either the contracts or transactions pages
3) view item and go back
4) list is now not filtered, and you are in a state of needing to filter again for a given chain

Proposed solution:
Separate mainnet and testnet entirely, reducing the need to filter.
**testnet.dora**
**dora**

**Comment by lock9** [comment]
Hi. We are going to fix that on issue #402 . I'll close this for now. Thanks
