### ISSUE TITLE
Address Information Header and Navigation

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#432]
# What is to be done?

- Implement changes to the **Fixed Header** of the Address Information Page
- Implement the **Navigation Buttons** that will toggle between views:
  - **Assets View**
  - **NFTs View**
  - **Transactions View**
- Change the page path to redirect to each View.
- Implement **Mobile version** of Header and Navigation

# Designs
- [**Desktop - Address Information - Assets**](https://app.avocode.com/view/cd7f5f287d0445ab9c33bd978be54081/_/inspect)
- [**Mobile - Address Information - Assets**](https://app.avocode.com/view/2113be7aa6d6460bb9ff7e4fc3cd3646/_/inspect)

# Implementation Notes
- Create blank pages for each view to navigate to with the buttons.
  - The content of these pages will be implemented by the upcoming issues.
- NFT button is only present for N3 Addresses.
- For **Mobile**: 
  - The requirements are the same, just the design needs to be adjusted.
- We need to change the path to each view:
  - current path:
    - `https://dora.coz.io/address/neo3/mainnet/ADDRESS_GOES_HERE`
  - new paths:
    - Assets View
      - `https://dora.coz.io/address/neo3/mainnet/ADDRESS_GOES_HERE`
    - NFT View
      - `https://dora.coz.io/address/neo3/mainnet/ADDRESS_GOES_HERE/nfts`
    - Transactions View
      - `https://dora.coz.io/address/neo3/mainnet/ADDRESS_GOES_HERE/transactions`

# Technical Requirements
## Fixed Header

- _image:_ **Wallet Icon**
- _page title:_ **Address Information**
- **Address Header Component:**
  - _label:_ **Address**
  - _image:_ **Network Logo**
  - _text:_ **Network Label**
  - _scripthash:_ **Address**
  - _button:_ **Copy**
    - (copies the Address to clipboard)

## Navigation
- _buttons_:
  - **Assets**
  - **NFTs**
    - Only present for N3 Addresses
  - **Transactions**
  - (clicking each button will toggle the page between the different views)

**Comment by EvCastie1** [comment]
The "assets, nfts view and trnsactions view" buttons are not showing, nor is the copy address button

![12345.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/1dc9154d-917b-4a75-a833-b67583ba1935)

**Comment by brunobass123** [comment]
fix the responsive only on the "Address Information Header and Navigation" screen

**Comment by EvCastie1** [comment]
fixed

![678.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/22b5a8ab-92e8-479d-b50e-49ea3e6e7a64)
