### ISSUE TITLE
NFTs View - List View

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#434]
# What is to be done?

- Implement the **NFTs List View:**
- Implement **Mobile version**.

# Designs
- [**Desktop - Address information NFTs List view**](https://app.avocode.com/revisions/85248968/?design=57227011)
  - Red square in NFT Image is just for alignment and resizing reference
- [**Mobile - Address information NFTs List view**](https://app.avocode.com/view/68554fb72e624bc3abf8c5ac53d7958f/_/inspect)

# Implementation Notes

- The **Gallery/List View Toggle Buttons** are out of scope, and will be implemented in an upcoming issue (#439).
- The **Collection Filter** is out of scope, and will be implemented in an upcoming issue (#443)
- For **Mobile**: 
  - There are some changes to component behaviour.
  - Check Requirements and Designs.

# Tech Resources
- Address with NFTs:
  - NekqQM4kT6MESNoFjyrpnnFPi2au6VLkAU
- Ghostmarket NFT list for that same address:
  - https://ghostmarket.io/account/n3/NekqQM4kT6MESNoFjyrpnnFPi2au6VLkAU/?tab=available
  - **Use this page only to test if we are returning the same content as Ghost Market.**
- We should use Ghost Market API to fetch NFT attributes.
  - Ask @picarodias  for the API Docs. 

# Technical Requirements

## NFTs View
List of NFTs owned by the address.

### NFTs List View 

- For each NFT held a list item must be rendered.
- On page load: Render **the first 6 NFT List Itens** by default.
- _button:_ **Load More**
  - (at the end of the list, renders **the next 6 NFT List Items**)

**NFT List Item:**
  - _image:_ **Token image**
    - (cropped to a **circular frame** | image Center aligned to the center of the Frame)
  - _image:_ **Collection Icon**
  - _text:_ **Token Name**
  - _text:_ **Collection Name** 
  - _label:_ **ID**
    - _number:_ **Token ID**
  - _button:_ **Right Arrow Icon**
    - (navigates to **NFT Information Page** for the given NFT)
  - **Attribute Component:**
    - _label:_ **Attribute Key**
    - _text/number_: **Attribute Value**
      - e.g.: **LP Yield Increase: 1%**, 
    - (render as many **Attribute Components** as can be fitted in a single line)
  - _button:_ **Plus Icon** / **Minus Icon**
    - (**Renders 2 more lines** of attribute components of the given NFT)
    - If there are more attributes to display:
      - _text:_ **+** X **more**
        - X = number of hidden attributes.
        - e.g.: **+ 20 more**

## Mobile Adjustments
Changes necessary for mobile implementation.

### NFTs List View 
**Attribute Components are removed.** Requirements are reduced to:

**NFT List Item:**
 - _image:_ **Token image**
    - (cropped to a **square frame** | image Center aligned to the center of the Frame)
  - _image:_ **Collection Icon**
  - _text:_ **Collection Name**
  -  _text:_ **Token Name**
  - _label:_ **ID**
    - _number:_ **Token ID**
  - _button:_ **Right Arrow Icon**
    - (navigates to **NFT Information Page** for the given NFT)

**Comment by EvCastie1** [comment]
the load more button is not showing, for viewing all NFTs

![9797.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/6f07c72d-ce8b-47a3-a455-663f3f4f3628)

**Comment by EvCastie1** [comment]
In the mobile version, the "lead more" button and the token figure are also not appearing.

![WhatsApp Image 2022-02-15 at 14.36.55.jpeg](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/d4789f67-aeae-4cf8-9498-1cca6934fa90)

**Comment by EvCastie1** [comment]
the "load more" button was implemented in both the desktop and mobile versions, but the token that was supposed to appear next to the NFT name is still not appearing according to the design

![WhatsApp Image 2022-03-08 at 11.17.34.jpeg](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/a05f79dc-8be2-4a80-9c10-0f7885735951)
