### ISSUE TITLE
NFTs View - NFT Information Page

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#435]
# What is to be done?

- Create the path for **NFT Information Page**
- Implement the **NFT Information Page**
- Implement **Mobile version** of **NFT Information Page**

# Designs
- [**Desktop - NFT Information**](https://app.avocode.com/view/a408472428be463fb46061c5712d2529/_/inspect)
- [**Desktop -NFT Information - image overlay**](https://app.avocode.com/view/31463635baa84bd4abf6a152b8276f12/_/inspect)
- [**Mobile - NFT Information**](https://app.avocode.com/view/f2cc1945d70340aea46e7ab6c33a20b9/_/inspect)

# Implementation Notes

- For the first implementation, this page will only be navigated to from the **NFT List View.**
- For **Mobile**: 
  - The requirements are the same, just the design needs to be adjusted.
  - We should use Ghost Market API to fetch NFT attributes.
    - Ask @picarodias  for the API Docs. 
- Path for NFT Information pages:
  - `https://dora.coz.io/nft/neo3/mainnet/CONTRACT_HASH/NFT_ID`

# Technical Requirements

## NFT Information Page
A page displaying the detailed information of a given NFT.

- _button:_ **back to address information**
  - (navigates back to **Address Information NFT View**)
- _image:_ **Diamond Icon**
- _page title:_ **NFT Information**

**NFT Header Component:**
  - _text:_ **Token Name**
  - _label:_ **ID**
    - _number:_ **Token ID**

**Token Image:**
- _image:_ **Token image**
  - (cropped to a **square frame** | image Center aligned to the center of the Frame)
- _button:_ **Magnifier Icon**
  - (clicking the icon opens the **NFT Image Enlargement Overlay**)

**NFT Image Enlargement Overlay:**
- _image:_ **Token image**
  - (full sized | image centered to the screen)
- _text:_ **Token Name**
- _overlay:_ **page in the background fades to black**

**Token Details:**
- _title:_ **DETAILS**
- _label:_ **DESCRIPTION**
  - _text:_ **Token Description**
- _label:_ **CREATOR**
  - _text:_ **Token Creator**
- _label:_ **COLLECTION**
  - _image:_ **Collection Icon**
  - _text:_ **Collection Name**
- _label:_ **SYMBOL**
  - _text:_ **Collection Symbol**
- _label:_ **BLOCKCHAIN**
  - _image:_ **Blockchain Icon**
  - _text:_ **Blockchain Name**
- _label:_ **CONTRACT**
  - _text:_ **Contract's Hash**
- _label:_ **TOKEN URI**
  - _text:_ **Token URI**

**Token Attributes**
- _title:_ **ATTRIBUTES**
- **Attribute Component:**
  - _label:_ **Attribute Key**
  - _text/number_: **Attribute Value**
  - (render an **Attribute Component** for each attribute of the given Token)

**Comment by picarodias** [comment]
Example of Nested Attributes

```
{
  "color: "blue",
  "appearance": {
    "finish": "shiny",
    "texture": "marbled",
    "opacity": "translucent"
  }
}
```

The above Key: Values Should be rendered:
- color: blue
- appearance.finish: shiny
- appearance.texture: marbled
- appearance.opacity: translucent

**Comment by EvCastie1** [comment]
the web version and the mobile version have different fonts, it's kind of weird in relation to the design

![7676.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/f11b46f1-88c9-413b-9867-305cfaf9eacd)

mobile version
![WhatsApp Image 2022-02-15 at 13.41.43.jpeg](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/b52fc573-5455-47bf-8ea4-838a8084c80c)

**Comment by EvCastie1** [comment]
the load more button is not showing, for viewing all NFTs

![9797.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/03787698-ae37-480e-b35f-91e0e3794558)

**Comment by EvCastie1** [comment]
fixed

![44332121.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/ca870f15-313a-4272-807b-3b4d117e8fec)
