### ISSUE TITLE
Transactions View

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#436]
# What is to be done?

- Implement the **Transactions View**
- Implement **Mobile version** of **Transactions View**

# Designs
- [**Desktop - Address information - Transactions**](https://app.avocode.com/view/f62259d8ee904653b5c4a74463e6b38f/_/inspect)
- [**Mobile - Address information - Transactions**](https://app.avocode.com/view/bd6592702d064a98af45126eba53978e/_/inspect)

# Implementation Notes

- For **Mobile**: 
  - There are some changes to component behaviour.
  - Check Requirements and Designs.

**UPDATE:**
- Not in the Design:
  - Add **Symbol Column** to both Desktop and Mobile.

## Tech Resources:

- We're using the new endpoint `address_txfull` to refactor this page:

### Endpoint URI:
[https://dora.coz.io/api/v1/neo3/mainnet/address_txfull/NTctCgu9xncCS58vkfWrP27Z6oDrq2N5e9/1](https://dora.coz.io/api/v1/neo3/mainnet/address_txfull/NTctCgu9xncCS58vkfWrP27Z6oDrq2N5e9/1)

### Transaction data model 
_extracted from the JSON returned above | just 1st layer_

```
{
	"block" : ,
	"hash" : ,
	"invocations" : ,
	"netfee" : ,
	"sender" : ,
	"sysfee" : ,
	"time" : ,
	"transfers" : ,
	"vmstate" : ,
	"notifications" : ,
},
```

# Technical Requirements

## Transactions View
List of transactions of the address.
- For each transaction, a list item must be rendered.
- On page load: Render **the first 4 Transactions** by default.
- _button:_ **Load More**
  - (at the end of the list | renders **the next 4 Transactions**)

**Transaction List Item:**
- _image:_ **Blockchain Icon**
- _text:_ **Blockchain Name**
- _label:_ **ID**
  - _text:_ **Transaction ScriptHash**
    - from the json: `hash`
- _image:_ **Calendar Icon**
  - _date:_ **Transaction Date**
    - from the json: `time` 
- _image:_ **Clock Icon**
  - _time:_ **Transaction Time**
    - from the json: `time` 
- _button:_ **Right Arrow**
  - (clicking the button navigates to the **Transaction Screen** of the given transaction)
- _label:_ **Notifications:**
  - _number:_ **n° of Notifications**
    - from the json: `notifications` 
      - count how many invocation objects exist inside
- _label:_ **Invocations**
  - _number:_ **n° of Invocations**
    - from the json: `invocations` 
      - count how many invocation objects exist inside
- If the transaction contains NEP-17 Transfer Events:
  - render a **NEP-17 Transfer Component** for each.

**NEP-17 Transfer Events:**
- _label:_ **From**
  - _text:_ **Sender address**
    - from the json: `transfers: from`
- _label:_ **To**
  - _text:_ **Recipient Address**
    - from the json: `transfers: to`
- _label:_ **Amount**
  - _image:_ **Token Icon**
  - _number:_ **Sent Token Amount**
    - from the json: `transfers: amount`
- _label:_ **Type**
  - _text:_ **NEP-17 Transfer**

## Mobile Adjustments
Changes necessary for mobile implementation.

**NEP-17 Transfer Events:**
Labels **To and From are removed.** Requirements are reduced to:
- _label:_ **Type**
  - _text:_ **NEP-17 Transfer**
- _label:_ **Amount**
  - _image:_ **Token Icon**
  - _number:_ **Sent Token Amount**
    - from the json: `transfers: amount`

**Comment by EvCastie1** [comment]
on the style #address-menu a has 170px on width and this creates a scrollable screen

it will need some fix even if remove this property, but the layout looks like a little better

![unknown.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/35ace992-b6ff-434f-8e2e-baea28598d44)

**Comment by picarodias** [comment]
We need to add the Symbol Column, like we currently have in production, **but aligned with the new style**.

_example from production:_
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/4ac729c8-b57e-4bfb-b85d-39a7d866cf78)

**Comment by aldo-maciel** [comment]
It needs some clarification about mobile design

**Comment by picarodias** [comment]
- Mobile designs updated in the issue.

**Comment by EvCastie1** [comment]
check the images of the tokens in the mobile version that are not changing according to the tokens

**Comment by EvCastie1** [comment]
fixed
