### ISSUE TITLE
Address page layout/loading defects

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/dora#463]
When switching between the tabs on the address page the layout / loading skeletons jump around it looks bad... This could be refined quite a bit and we should not release the app in this state.

![Kapture 2022-02-10 at 07 32 20](https://user-images.githubusercontent.com/13072035/153429487-85ef8e00-6fb6-47e4-b7d4-e789e3a9ec11.gif)

Technical notes: 
- Its probably not the most performant to make these network requests every time a tab is clicked here rather cache the data so that it can instantly load when a tab is cycled
- we should probably have an address page "container" component so that the tabs and address component do not reload on every screen render

**Comment by EvCastie1** [comment]
fixed

https://images.zenhubusercontent.com/258331310/0d335279-915d-4dd3-b86b-b82c77b8057b/2022_03_08_14_50_48.mp4
