### ISSUE TITLE
Add Short Commit Hash to Dora's Footer.

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#484]
## What is to be done?

- Include the short commit hash of latest GitHub commit to dora's fixed footer.

## Technical notes:
- Latest commit can be found in the following URL:
  - https://github.com/CityOfZion/dora/commits/develop
- We just need to display **the first 7 characters of the hash**, like in the GitHub preview:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/1b697b2d-fe87-4f89-9b35-535db7ca5624)

## Visual Reference

- There is no Design for this. 
- Use the same font style used in **2022 Copyright** in the screenshot below.
- Text goes on the far right, as indicated. 
- Align the text with the text on the left side.

![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/2c682508-eec6-45b2-a4e7-e92add1b80f0)

**Comment by Zidious** [comment]
Hey guys 👋 , I see a PR has been merged but I do not see the SHA in the footer. Thoughts on the implementation shown below? 

We could possibly set ENV variables to determine Dev vs Prod. Example: 

Two ENV vars: 
`GET_SHA_DEV = 'develop'` 
`GIT_SHA _PROD = 'master'`

```ts
export const fetchGitSha() { 
	let url = '';
	if (GIT_SHA _PROD) {
 		url = `https://api.github.com/repos/CityOfZion/dora/branches/${GIT_SHA _PROD}`
	} else { 
		url = `https://api.github.com/repos/CityOfZion/dora/branches/${GET_SHA_DEV}`
	}

	// fetch JSON 
	// see data shape - https://api.github.com/repos/CityOfZion/dora/branches/develop
	// const sha = res.commit.sha.substring(0, 6)
	// const shaUrl = res.commit.commit.url
	return { sha, shaUrl }
}
```

Let me know!

**Comment by ixje** [comment]
looks already implemented
