### ISSUE TITLE
Legacy Mainnet Blocks and Transactions zeroed since yesterday (03/03)

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#486]
## The Issue:

- No data for Legacy blocks and transactions since yesterday.

## Tech Notes and Evidence:
_All screenshots taken on march 4, 2022, around 14h UTC_
1. Zeroed transactions for a day:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/6fa29876-790c-49b4-9f6d-062a45f294cc)

2. Blocks stopped for a day:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/b01ac804-513e-4754-bb51-92493af0f487)

3. But Monitor page shows that Nodes are available, and has the correct block count:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/a2cd006e-f1b7-4513-a1ab-3b3af9e86b9c)

4. NeoTracker also seems to be getting blocks and transactions just fine:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/28e34ace-48fc-4d61-8a9d-d889e710a4e2)
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/9a4c0e2b-abaa-4856-b5a2-1241ce283a51)

**Comment by hal0x2328** [comment]
This was a service state issue related to the recent ApplicationLogs DoS condition that affected all TestNet nodes, it has been resolved now.
