### ISSUE TITLE
Add Chain Identifier to Header (Mainnet x Testnet)

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#490]
## What is to be done?

- Include (MainNet x TestNet) identifier to page Header Component.

## Implementation Notes

- Include a parenthesis to the Network Identifier:

### Mainnet:
**Neo N3 (Mainnet)**
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/d0274fcd-3f07-45f5-84ff-3c88b0f2613d)

### TestNet:
**Neo N3 (Testnet)**
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/11fee2b9-328e-4369-b2e1-26f5be8946f7)

**Comment by EvCastie1** [comment]
fixed


![739.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/063514c3-9481-4dc8-b76e-c4e4836a6eb1)![740.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/46a8ffd5-62ea-4c8e-940f-af028f9d3c48)
