### ISSUE TITLE
Fix Issue: NFTs View - load 8 NFTs each time.

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#491]
## What is to be done?

- Change the amount of NFTs being loaded each time, from 6 to 8.
- This will impact both List View and Gallery View.

**Comment by EvCastie1** [comment]
fixed

https://images.zenhubusercontent.com/258331310/a6b05632-f398-4d7c-8301-bfa169206459/2022_03_09_11_44_14.mp4
