### ISSUE TITLE
Fix Issue: NFT Details Page

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#492]
## The Issue:
_refer to issue #435 for full requirements_
- NFT Details Page stopped working:

![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/e31eb064-9d69-4aef-99cc-23eabf0874a6)

**Comment by EvCastie1** [comment]
fixed in the desktop version and in the mobile version

![7676.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/6405fc05-6cbd-484b-9930-b62e52f13a70)
