### ISSUE TITLE
Address Details -> Fix usage of address_txfull endpoint

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#496]
## What is to be done?

- We should use the `notifications` object, instead of the `transfers` object.
- Fetch Transfer events inside the `notifications` object.
  - Transfer Events with depth of 3 are Nep-17 Transfers and should be rendered.
  - Transfer Events with depth 4 should be ignored for now.

## Example data

Inside a Transfer Notification with a state containing 3 parameters:
- 1st param = From
- 2nd param = To
- 3rd param = Amount

```
"notifications": [
        {
          "contract": "0xf0151f528127558851b39c2cd8aa47da7418ab28",
          "event_name": "Transfer",
          "state": [
            {
              "type": "ByteString",
              "value": "VIXGSTwV6kv7oAteiHQIrUeaBVo="
            },
            {
              "type": "ByteString",
              "value": "Qhxy8GdZeEWKFwjWaMmTcZrwy2s="
            },
            {
              "type": "Integer",
              "value": "364528351371"
            }
          ]
        },
```

**Comment by picarodias** [comment]
Tranactions tab not loading for this address:
https://dora-stage.coz.io/address/neo3/mainnet/NbSMUDAbB3xsr3Y1mqX2sa2R1XmoaF9Qum/transactions

throwing this error.
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/18ad3aeb-9c2a-4c8c-8348-71dfcc63f0a6)

**Comment by picarodias** [comment]
The error above was caused by facing Transfer Notifications where either `from` or `to` parameters were empty. We're adopting the following strategy based on conversation with @lock9 :
- When `from` is empty: `from`= `mint`
- When `to` is empty: `to`= `burn`

**Comment by EvCastie1** [comment]
Fixed

![999.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/1b2d784d-8951-4322-be07-e30a5d9f0f46)
