### ISSUE TITLE
Fixes to Transactions Tab

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#503]
## What is to be done?

- (1) Render Token's Symbol in the Symbol Column :
  - We're currently showing the `name` field. 
  - We should show the `symbol` field instead.
  - Also fix truncate to max length of 8 characters.
  - This information should be returned by the same endpoint currently being used (`assets`).
- (2) When we have no **NEP-17 Transfers** in a transaction to render:
  - Remove error message (not found transfers).
  - Remove Column Headers:
    - From
    - To
    - Symbol
    - Amount
    - Type

## Reference

(1) Name being rendered instead of Symbol: Symbol for NeoToken is NEO; Symbol for GasToken is GAS.
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/43c19c93-5e40-4f82-906c-d1258bd89c40)

(2) Remove Error message and Column Headers. Transactions should be blank, with only Notifications and Invocations on the far-right.
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/61ed562d-7574-4a5d-b929-62929184adf6)

**Comment by EvCastie1** [comment]
Fixed

![7777.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/3f5befd2-a09b-4729-92ea-c4e26d4b556b)

![9991.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/0774d719-4324-4076-84eb-880674f69035)
