### ISSUE TITLE
Bug: Transactions Tab doesn't load when accessed directly through URL

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#510]
## The Bug:

- If the user navigates directly to the Transactions Tab URL, it displays **No transactions to list** message.
  - https://dora-stage.coz.io/address/neo3/mainnet/NekqQM4kT6MESNoFjyrpnnFPi2au6VLkAU/transactions
  - https://dora-stage.coz.io/address/neo3/mainnet/NNmTVFrSPhe7zjgN6iq9cLgXJwLZziUKV6/transactions
- Transactions will only load after clicking the Assets Tab, and then returning to the Transactions Tab.
  - Clicking the NFT tab doesn't have the same effect, transactions are still not found.

**Comment by EvCastie1** [comment]
fixed
