### ISSUE TITLE
Adjust how we display NFT image in NFT Detail screen

### ISSUE THREAD

**Issue by thiagocbalducci** [CityOfZion/dora#515]
Right now, as per example below, when we display the NFT detail page, the image is being clipped based on its width value, we should resize it based on the dimension with the higher value between width and height.

The same logic should be applied to the zoomed in version, when we click the image.

* https://dora-stage.coz.io/nft/neo3/testnet_rc4/0x97857c01d64f846b5fe2eca2d09d2d73928b3f43/12849 <- we scale to width here, which prevents the entire image from being displayed.  This is ok on the overview pages, but we should scale to the max dimension so the entire image is displayed

**Comment by EvCastie1** [comment]
fixed

![1111.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/23eb7a65-706a-4c3a-be19-22883ca1e7b6)![222222.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/87ec2235-d0d5-41c3-aac8-617815419a1d)
