### ISSUE TITLE
Fix Addresses to Link Style

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#544]
# What is to be done?

- **Transfer Events** (top component of the page):
  - Fix Address to Link Style

# Design

- [Transaction Information Page](https://app.avocode.com/revisions/86600065/?design=58108551)

# Technical Notes

- For some reason addresses are being rendered in white.

# Requirements

## Transfer events
**Existing Section**

- Address links must be pink.

**Comment by picarodias** [comment]
This should be assigned to Thais

**Comment by EvCastie1** [comment]
When hovering the mouse over the link, the "hand" does not appear, which is understood to be a link

and on the right side too, but only up to half of the wallet.

**Comment by EvCastie1** [comment]
fixed
