### ISSUE TITLE
Transaction Details Section

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#545]
# What is to be done?

- **DETAILS** Section:
  - Implement **VM State Panel**
  - Implement **Trigger Panel**

# Design

- [Transaction Information Page](https://app.avocode.com/revisions/86600065/?design=58108551)
  - **Out of Scope: Invocation Panel**

# Technical Notes

- **VM State** and **Exception** are returned by the [`log`](https://dora.coz.io/api/v1/neo3/mainnet/log/0xeece28a1d311e7548e4ee1674778d689a3817f3f786dd8ce20f9f701f02b32f3) endpoint.

# Requirements

## Details
**Existing Section**
Add new blocks of information.

- _label:_ TRIGGER
  - possible values: 
    - Application
    - OnPersist
    - PostPersist
    - Verification
    - System
    - All
    
- _label:_ VM STATE
  - possible values (Colorcoded):
    - HALT (Green)
    - FAULT (Red)

**If VM STATE equals FAULT**, the panel expands to show: 
- _label:_ EXCEPTION
  - _text:_ Error returned by the exception.
  - _button:_ Copy
    - On Click: Copies error message to the clipboard

**Comment by picarodias** [comment]
This should be assigned to Lopes.

**Comment by EvCastie1** [comment]
fixed

![3.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/da594bc8-3c04-408a-b580-2c35342909ca)

![4.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/7750a049-483d-4280-bd94-956919d92ecd)
