### ISSUE TITLE
RAW Script and Disassembled Script Sections

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#546]
# What is to be done?
- Reorder sections and add Copy button to both of them:
  - **Raw Script**
  - **Disassembled Script**

# Design
- [Transaction Information Page](https://app.avocode.com/revisions/86600065/?design=58108551)
  - Implement one copy button for each Script Panel:
    - Script
    - Invocation
    - Verification

# Requirements
**Both Sections are collapsed on page load.**

## Raw Script
**Existing Section**

- Move it to the end of the page
- Add Copy button:
  - On Click: Copies Raw Script to the Clipboard

## Disassembled Script

- Move it to the end of the page
- Add Copy button:
  - On Click: Copies Raw Script to the Clipboard

**Comment by ixje** [comment]
> ## Disassembled Script
> * Move it to the end of the page
> * Add Copy button:
>   
>   * On Click: Copies Raw Script to the Clipboard

I assume the `On Click` should copy the `Disassembled script` here, not the `raw script`?

**Comment by EvCastie1** [comment]
The font is different than the one without layout

![unknown (1).png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/862f34ef-ffb8-4347-ad2f-096df0234ea3)

![1.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/a62dc3e5-ba8a-45a0-9ce9-73802373549a)

**Comment by EvCastie1** [comment]
Fixed 

![5.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/949d392b-3972-4788-885a-880b9f1e0c16)

**Comment by ixje** [comment]
looks already done
