### ISSUE TITLE
Notifications Section

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#547]
# What is to be done?

- Implement the new **Notifications** section.
  - It will replace current single _Notifications_

# Designs

[Transaction Information Screen](https://app.avocode.com/view/7a94d790b0704fef941e6138aef7a477/_/inspect)

# Technical Notes

- **Notifications** are returned by the [`log`](https://dora.coz.io/api/v1/neo3/mainnet/log/0xeece28a1d311e7548e4ee1674778d689a3817f3f786dd8ce20f9f701f02b32f3) endpoint.

# Requirements

## Notifications

**New Section, replaces current Notifications**
We're gathering the existing single notifications into a unified section. Same interface that exists for Invocations.

- _section title:_ Notifications

For each Notification (expandable, starts closed):

- _text:_ Contract Name
- _label:_ HASH
  - _hash:_ Contract Hash
  - _button:_ Copy
    - On Click: Copies Hash to the Clipboard 
- _text:_ Method Name
- for each Parameter in the Notification:
  - _number:_ Parameter Index
  - _text:_ Parameter Name 
  - _label:_ Parameter Type
  - _dropdown:_ Toggle Type
  - _text:_ Parameter Value
  - _button:_ Copy
    - On Click: Copies Parameter Value to the clipboard

If Parameter is an Array:
- Render items in the array as nested parameters.
- For nested parameters, **don't render**
  - Parameter Name
  - Parameter Type
- If any item in the Array is another Array, just render it's content as a string.

**Comment by picarodias** [comment]
This should be assigned to Lopes.

**Comment by picarodias** [comment]
How to handle Notification Data:

- The first array inside the `state` object contains the actual parameters of the Notification.
- The objects inside this array are the first layer that we are showing.
- In the example below, we have a Transfer notification with 3 Parameters:
  - [0] type **ByteString**
  - [1] type **ByteString**
  - [2] type **Integer**
- The parameter name for each parameter needs to be fetched directly from the contract.
```
"notifications": [
    {
      "contract": "0x4d5a85b0c83777df72cfb665a933970e4e20c0ec",
      "event_name": "Transfer",
      "state": {
        "type": "Array",
        "value": [
          {
            "type": "ByteString",
            "value": "Y2/EnjqWCjTyTe8vMvZAGY73qdE="
          },
          {
            "type": "ByteString",
            "value": "sauBFWpABIqMVKqIyqVALi1yCo8="
          },
          {
            "type": "Integer",
            "value": "157182850557"
          }
        ]
      }
    },
```

**Comment by picarodias** [comment]
## Mock data 
- `log` endpoint return for a Transaction with `array` type notification parameter:
  - Important: the second object in the array parameter is also an array. We're only treating one level of arrays, this second layer array shall be rendered as raw data.

```
{    
    "txid": "0xb415494b90c405bdc43307791f476590b48ed0060f1fc57af2781d53b189c581",
    "trigger": "Application",
    "vmstate": "HALT",
    "exception": null,
    "gasconsumed": "2644200",
    "stack": [
        {
            "type": "Any"
        }
    ],
    "notifications": [
        {
            "contract": "0xf131d4efe5f4c53d937b1a6a8d3e0aedd5e36673",
            "eventname": "DoraTestEvent",
            "state": {
                "type": "Array",
                "value": [
                    {
                        "type": "ByteString",
                        "value": "Y296"
                    },
                    {
                        "type": "Integer",
                        "value": "123"
                    },
                    {
                        "type": "Array",
                        "value": [
                            {
                                "type": "ByteString",
                                "value": "SGVsbG9Xb3JsZA=="
                            },
                            {
                                "type": "Array",
                                "value": [
                                    {
                                        "type": "Integer",
                                        "value": "456"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        }
    ],
    "time": "1649253875.135000"
}
```

- `contract` endpoint return for the mock contract invoked in the transaction above.
```
{
    "id": 1,
    "updatecounter": 0,
    "hash": "0xf131d4efe5f4c53d937b1a6a8d3e0aedd5e36673",
    "nef": {
        "magic": 860243278,
        "compiler": "neo3-boa by COZ-0.11.2.0",
        "source": "",
        "tokens": [],
        "script": "DALIAdshEcAMCkhlbGxvV29ybGQSwAwBe9shDANjb3oTwAwNRG9yYVRlc3RFdmVudEGVAW9hQA==",
        "checksum": 3210064150
    },
    "manifest": {
        "name": "DoraTestContract",
        "groups": [],
        "features": {},
        "supportedstandards": [],
        "abi": {
            "methods": [
                {
                    "name": "AppLogEvent",
                    "parameters": [],
                    "returntype": "Void",
                    "offset": 0,
                    "safe": false
                }
            ],
            "events": [
                {
                    "name": "DoraTestEvent",
                    "parameters": [
                        {
                            "name": "param1_name",
                            "type": "String"
                        },
                        {
                            "name": "param2_amount",
                            "type": "Integer"
                        },
                        {
                            "name": "param3_data",
                            "type": "Array"
                        }
                    ]
                }
            ]
        },
        "permissions": [
            {
                "contract": "*",
                "methods": "*"
            }
        ],
        "trusts": [],
        "extra": {
            "Author": "COZ ",
            "Email": "contact@coz.io",
            "Description": "This is a contract example"
        }
    },
    "block": 601352,
    "time": "1637299558.984000",
    "last_update": "1651389549.016000"
}
```

**Comment by picarodias** [comment]
Notifications contain more arguments then they should. Check this transaction:
https://dora-stage.coz.io/transaction/neo3/mainnet/0xd0096092358b1d3177d2b2bd7dd3e081158017eb898c6f50297d36ad8e3e5679

First notification is a FLM Transfer, and is showing 8 arguments:
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/a039944d-aa3d-4447-9e60-e731b53236cc)

In the [return from the endpoint](https://dora.coz.io/api/v1/neo3/mainnet/log/0xd0096092358b1d3177d2b2bd7dd3e081158017eb898c6f50297d36ad8e3e5679), we see that it should only contain 3 arguments:
```
  "notifications": [
    {
      "contract": "0xf0151f528127558851b39c2cd8aa47da7418ab28",
      "event_name": "Transfer",
      "state": {
        "type": "Array",
        "value": [
          {
            "type": "ByteString",
            "value": "e1vuNecCDLFBwsvS1yr9zq/eru8="
          },
          {
            "type": "ByteString",
            "value": "F0OpTtzVrKr5CBhPOIR9T6uKeNg="
          },
          {
            "type": "Integer",
            "value": "79636937377"
          }
        ]
      }
    },
```

**Comment by picarodias** [comment]
Another strange behaviour changes the number of arguments that are shown:

## Navigating back and forth from the page
- Click an address in the first block of the page to navigate to the Address Information Page.
- Click back on the browser to return to the Transaction.
- New fake arguments will appear in the notification.

## Zooming the page in the browser

- Zooming in and out will cause more fake arguments to appear indefinnetly.

_screenshot with 110 arguments in the same transfer notifications:_
![image.png](https://images.zenhubusercontent.com/60143ce729dc0d5c5b91324f/31bebb2d-bec1-41bb-8817-c10b6216bc86)

**Comment by EvCastie1** [comment]
fixed

![6.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/0e5619d8-e3fe-401a-8ffa-46ebddfaa811)
