### ISSUE TITLE
Signatures Section

### ISSUE THREAD

**Issue by picarodias** [CityOfZion/dora#549]
# What is to be done?

- Implement the new **Signatures** section.
  - Replaces existing _Signers Section_

# Designs

[Transaction Information Screen](https://app.avocode.com/view/7a94d790b0704fef941e6138aef7a477/_/inspect)

# Technical Notes

- Data returned by the [`transaction`](https://dora.coz.io/api/v1/neo3/mainnet/transaction/0x5d973fa1e6e4fdddac08aa8e76ef849ff23f981adc69c7312f0315dd99ee5070) endpoint.

# Requirements

**Replaces the existing Signers section**

- _section title:_ Signatures

For each address signing the transaction:

- _label:_ Signer
- _address:_ signer's address
- _button:_ Copy
  - On Click: Copies address to the clipboard
- _text:_ Signature Scope
  - possible values:
    - None
    - Call by Entry
    - Global
    - Custom Contracts
    - Custom Groups
  - For Custom Contracts and Custom Groups, component is expandable:
    - List of allowed Contracts or Groups

**Comment by EvCastie1** [comment]
fixed according to layout

![2.png](https://images.zenhubusercontent.com/61fc357e0716a0e5890efc67/6cbae40e-8d50-4af3-9f51-c3bb663caecf)
