### ISSUE TITLE
Monitor Tab: add endpoints for RPC nodes hosted by NeoSPCC

### ISSUE THREAD

**Issue by AnnaShaleva** [CityOfZion/dora#655]
##### Suggestion

There's a set of public, compatible and up-to-date RPC nodes in N3 and Legacy that are hosted and continuously maintained by [NeoSPCC team](https://github.com/nspcc-dev). It would be nice to integrate them with Dora web-site so that they they can be displayed in the Monitor tab along with NGD, COZ and other official public nodes:
![image](https://github.com/CityOfZion/dora/assets/22775709/0fb97da3-776d-4f1f-9b44-0a2dadf04ed7)

##### Endpoints list

The endpoints list can be found at https://github.com/CityOfZion/neon-wallet/pull/2558.

Thank you for considering my suggestion!

**Comment by ixje** [comment]
Missed this. The linked PR only adds these 2
mainnet - https://rpc10.n3.nspcc.ru:10331 (v0.103.1)
t5 - https://rpc.t5.n3.nspcc.ru:20331 (v0.103.1)

but the following MainNet urls also work
* https://rpc1.n3.nspcc.ru:10331 (v0.103)
* https://rpc2.n3.nspcc.ru:10331 (v0.103)
* https://rpc4.n3.nspcc.ru:10331  (v0.103)
* https://rpc5.n3.nspcc.ru:10331 (v0.103)
* https://rpc7.n3.nspcc.ru:10331 (v0.103)
* 3,8 & 9 time out

Should I add all or just the 2 from the other PR?

**Comment by ixje** [comment]
Also do you care about what the location says? e.g. https://rpc10.n3.nspcc.ru:10331/ seems to resolve to germany, but I can set the country to anything you like

**Comment by AnnaShaleva** [comment]
@ixje, sorry for the late answer, I just saw the notification.

> Should I add all or just the 2 from the other PR?

The `https://rpc[1-9].n3.nspcc.ru:10331/` RPC nodes that you've provided are not for public usage of N3 mainnet/testnet, these are NeoFS utilities, so you don't need to add them. Only 2 from https://github.com/CityOfZion/neon-wallet/pull/2558 are expected to be exposed.

> Also do you care about what the location says?

Let it be as is, it's just a place where we host our node, and it's OK for the resolved location to be displayed.

**Comment by ixje** [comment]
I've added them to the backend. They will show up on the next deployment.
