### ISSUE TITLE
Delay with the balance endpoint

### ISSUE THREAD

**Issue by lopescode** [CityOfZion/dora#664]
Hey guys, how’s it going?

I’ve been noticing some delays with the balance endpoint. 

https://dora.coz.io/api/v2/neo3/mainnet/balance/NNmTVFrSPhe7zjgN6iq9cLgXJwLZziUKV6

Could you help me investigate what might be going on?

The scenario I noticed is as follows: a user with 1 GAS transfers this 1 GAS to another account, and the time it takes for the balance to update in the wallet is sometimes exceeding 5 minutes. It’s been intermittent… I’ve seen cases where it takes around 3 minutes, others 7 minutes, and so on.

Is this the normal refresh rate for balance info in Dora?

I’d really appreciate your help with this! 😊

**Comment by revett** [comment]
@lopescode Thanks for the report, I've spent some time this evening investigating, but can't find anything wrong in the code.

This week I will do some testnet testing, and see if I can reproduce it. 

Does Neon do any caching of balances?

**Comment by ixje** [comment]
The backend does 0 caching, but there's is some caching applied (either in cloudflare or nginx). However, non of those exceed 1 minute afaik. I ask someone with access to those parts to verify the rules

**Comment by revett** [comment]
Tested this manually on testnet:

https://dora.coz.io/transaction/neo3/testnet/0x6bbd6e7ec693c90be73c9a31ce49ab75e8376f0635858695e0cf4ce551c638f0

- The tx was created at `15:17:12`
- It appeared in Dora near instantly
- The balance change of the `from` address updated at `15:21:10`
- The banace change of the `to` address updated at `15:21:46`

All of this was checked using API endpoints.

Going to continue investigating, given I've been able to reproduce the issue.

**Comment by revett** [comment]
cc/ this [message](https://discord.com/channels/940667734692356136/1088710944068210698/1292822630113742890) in Discord.

There is a 500 second cache on some requests, via AWS CloudFront.

@lopescode We are discussing as a team about changing this.

**Comment by lopescode** [comment]
Thank you Dex, I can't see the message you mentioned but I'll wait for updates here 😄

**Comment by lopescode** [comment]
@revett Answering your question about Neon caching... I don't know, I'm a member of NNT, I don't work at Neon anymore. But I know they are facing the same problem as me

**Comment by revett** [comment]
I have updated the cache TTL for the `/balance` endpoint from 500 seconds to 120 seconds.
